import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: {
		main: resolve(__dirname, "main.ts"),
		styles: resolve(__dirname, "src/ui/styles/index.css"),
	},
	bundle: true,
	jsx: "automatic",
	loader: {
		".ts": "ts",
		".tsx": "tsx",
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: resolve(__dirname),
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
